image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.

variables:
  DOCKER_DRIVER: overlay2
  GIT_SSL_NO_VERIFY: 1

stages:
 - build

build:
  stage: build
  script:
   - docker login ${DOCKER_REPO} -u ${DOCKER_REPO_USER} -p ${DOCKER_REPO_PASS}
   - docker build -t softwareplumbers/gradle-centos:${CI_COMMIT_REF_NAME} .
   - docker tag softwareplumbers/gradle-centos:${CI_COMMIT_REF_NAME} ${DOCKER_REPO}/softwareplumbers/gradle-centos:${CI_COMMIT_REF_NAME}
   - docker push ${DOCKER_REPO}/softwareplumbers/gradle-centos:${CI_COMMIT_REF_NAME}

