image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
#variables:
#  DOCKER_DRIVER: overlay2

services:
 - docker:dind

before_script:
 - apk add --no-cache curl jq python py-pip
 - pip install awscli

stages:
 - build

build:
  stage: build
  script:
   - $(aws ecr get-login --no-include-email --region us-east-1)
   - docker build -t softwareplumbers/gradle-centos:${CI_COMMIT_REF_NAME} .
   - docker tag softwareplumbers/gradle-centos:${CI_COMMIT_REF_NAME} 148956472318.dkr.ecr.us-east-1.amazonaws.com/softwareplumbers/gradle-centos:${CI_COMMIT_REF_NAME}
   - docker push 148956472318.dkr.ecr.us-east-1.amazonaws.com/softwareplumbers/gradle-centos:${CI_COMMIT_REF_NAME}

