# action.yml
name: 'Gradle build action'
description: 'Run a gradle build task in a defined environment'
inputs:
  gradle-task:  
    description: 'Gradle task to run'
    required: true
    default: 'build'
  username:
    description: 'User name for repository access'
    required: false
  password:
    description: 'Password for repository access'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gradle-task }}
  env:
    GITHUB_ACTOR: ${{ inputs.username }}
    GITHUB_TOKEN: ${{ inputs.password }}    